/* Shani Traders — English / Hindi text for the website.
   To change any wording, edit it here. {x} marks are filled in by the site. */
window.LANG = {
en: {
  'lang.other': 'हिंदी', 'lang.aria': 'हिंदी में देखें',
  'skip': 'Skip to content',
  'nav.home': 'Home', 'nav.products': 'Products', 'nav.calc': 'Calculator', 'nav.about': 'About us', 'nav.contact': 'Contact',
  'nav.list': 'Enquiry list', 'nav.menu': 'Menu',
  'f.talk': 'Talk to us', 'f.shop': 'Shop', 'f.whatsapp': 'WhatsApp',
  'f.note': 'Prices shown are indicative and confirmed at the time of order.', 'f.by': 'Website by',
  'wa.generic': 'Namaste {shop}, I have an enquiry.',
  'wa.product': "Namaste {shop}, please share today's price and availability:\n{item}", 'wa.qty': 'Quantity: {q} {unit}',

  'card.add': 'Add to list', 'card.out': 'Out of stock', 'card.per': 'per {unit}', 'card.ask': 'Ask for price',
  'card.waAria': 'Ask about {name} on WhatsApp', 'toast.added': '{name} added', 'toast.view': 'View list',
  'items.n': '{n} items', 'items.1': '1 item',

  'title.home': 'Shani Traders | Building material in Saraipali',
  'title.products': 'Products | Shani Traders, Saraipali', 'title.enquiry': 'Enquiry | Shani Traders',
  'title.about': 'About us | Shani Traders, Saraipali', 'title.contact': 'Contact | Shani Traders, Saraipali',
  'title.calc': 'Material calculator | Shani Traders, Saraipali',

  'h.title': 'Everything your building needs, from the foundation up.',
  'h.alt': 'नींव से छत तक, सारा सामान एक ही दुकान पर।', 'h.altLang': 'hi',
  'h.sub': 'Cement, sariya, bricks, sand, plumbing, wiring, tiles and paint in Saraipali. Make a list, send it to us, and we call back with the best rate and delivery time.',
  'h.browse': 'Browse products', 'h.wa': 'Ask on WhatsApp', 'h.waMsg': "Namaste {shop}, I want today's rates for building material.",
  'h.rates': "Today's rates", 'h.loading': 'Loading rates…', 'h.ratesErr': "Rates could not load. Call or WhatsApp us for today's prices.",
  'h.rbAsk': 'Ask', 'h.rbFoot': 'Rates move with the market. {link} for a confirmed price with delivery.', 'h.rbLink': 'Send your list',
  'h.shopBy': 'Shop by stage of work', 'h.shopBySub': 'Pick what you are building right now. Every item can be added to one enquiry list.',
  'h.askUs': 'Ask us',
  'h.calcTitle': 'Not sure how much to buy?',
  'h.calcSub': 'Enter the size of the wall, slab or room. The calculator tells you how many bricks, bags of cement and trolleys of sand you need.',
  'h.calcBtn': 'Open the calculator',
  'h.how': 'How ordering works',
  'h.s1t': 'Make your list', 'h.s1': 'Add items and quantities from the catalogue, or work them out with the calculator.',
  'h.s2t': 'Send it to us', 'h.s2': 'Send the list on WhatsApp or through the enquiry form. Both reach the shop straight away.',
  'h.s3t': 'Get a confirmed rate', 'h.s3': 'We call back with the final price, GST bill and delivery time to your site.',
  'h.strip': 'Building a house or a shop? Send the full material list once and get one rate for everything.',
  'h.stripBtn': 'Start an enquiry',

  'p.title': 'Products', 'p.sub': 'Prices are per unit shown. Final rate depends on quantity and delivery distance.',
  'p.searchLbl': 'Search products', 'p.search': 'Search cement, sariya, eent, pipe…', 'p.sort': 'Sort',
  'p.rec': 'Recommended', 'p.low': 'Price: low to high', 'p.high': 'Price: high to low', 'p.name': 'Name A to Z',
  'p.all': 'All', 'p.cat': 'Category', 'p.in': '{count} in {cat}',
  'p.none': 'Nothing matches “{q}”. We stock more than we list, so ask us for it.', 'p.noneWa': 'Namaste {shop}, do you have {q}?',
  'p.err': 'The product list could not load. Check your internet and refresh, or ask us directly.',

  'pd.loading': 'Loading…', 'pd.missing': 'This item is not available on the site right now.', 'pd.all': 'See all products',
  'pd.in': 'In stock', 'pd.out': 'Out of stock right now', 'pd.less': 'Less', 'pd.more': 'More', 'pd.qty': 'Quantity in {unit}',
  'pd.add': 'Add to enquiry list', 'pd.wa': 'Ask on WhatsApp', 'pd.waBack': 'Ask when it is back',
  'pd.brand': 'Brand', 'pd.soldPer': 'Sold per', 'pd.cat': 'Category', 'pd.related': 'More from this category', 'pd.photo': 'Photo',

  'e.title': 'Your enquiry', 'e.sub': 'Send your list and we call you back with the rate and delivery time. No payment is taken online.',
  'e.items': 'Items', 'e.clear': 'Clear list', 'e.clearQ': 'Remove all items from the list?',
  'e.empty': 'Your list is empty. Add items from the catalogue, use the calculator, or just write what you need in the message.',
  'e.remove': 'Remove', 'e.sendWa': 'Send this list on WhatsApp', 'e.waMsg': 'Namaste {shop}, please share rates for:\n{list}',
  'e.browse': 'Browse products', 'e.details': 'Your details', 'e.name': 'Name', 'e.phone': 'Mobile number', 'e.phonePh': '10-digit number',
  'e.place': 'Village or town', 'e.delivery': 'Delivery', 'e.d1': 'Deliver to my site', 'e.d2': 'I will pick up from shop', 'e.d3': 'Not decided yet',
  'e.email': 'Email', 'e.optional': '(optional)', 'e.emailHint': 'We send a copy of your enquiry here.',
  'e.msg': 'Anything else?', 'e.msgPh': 'Items not on the site, size of the house, when you need the material…',
  'e.send': 'Send enquiry', 'e.sending': 'Sending…',
  'e.errName': 'Enter your name.', 'e.errPhone': 'Enter a 10-digit mobile number.', 'e.errEmpty': 'Add items to your list or write what you need in the message.',
  'e.done': 'Enquiry sent', 'e.doneMsg': 'Your reference is {id}. We will call you on {phone} soon.', 'e.doneMail': ' A copy is on its way to your email.',
  'e.back': 'Back to products', 'e.errAlt': 'You can also {link}.', 'e.errLink': 'send it on WhatsApp',
  'e.waForm': 'Namaste {shop}, new enquiry\nName: {name}\nMobile: {phone}\nPlace: {place}\nDelivery: {delivery}\n\n{list}\n\n{msg}',

  'a.title': 'About Shani Traders',
  'a.lead': 'Shani Traders supplies building material to families, shop owners and contractors in and around Saraipali, from the first bag of cement to the last coat of paint.',
  'a.p': 'Our shop is on Main Road, Patsendri. We keep the material a house needs at every stage, so you can buy from one counter instead of five, get one bill and one delivery schedule.',
  'a.f1t': 'Known brands', 'a.f1': 'Cement, steel, pipes, wire and paint from brands masons and engineers already trust.',
  'a.f2t': 'GST bill on every order', 'a.f2': 'A proper tax invoice for every purchase, useful for home loans and business accounts.',
  'a.f3t': 'Delivery to your site', 'a.f3': 'Sand, gitti, bricks and heavy items delivered by tractor and pickup to your site.',
  'a.f4t': 'Fair daily rates', 'a.f4': 'Rates follow the market. Ask before you buy and we tell you the price for your quantity.',
  'a.btn': 'See products',

  'c.title': 'Contact', 'c.sub': 'Call, WhatsApp or visit the shop.', 'c.address': 'Address', 'c.phone': 'Phone', 'c.email': 'Email',
  'c.hours': 'Shop timings', 'c.gstin': 'GSTIN', 'c.call': 'Call the shop', 'c.form': 'Enquiry form', 'c.map': 'Shop location on map',

  'calc.title': 'Material calculator',
  'calc.sub': 'Enter sizes in feet. Results include a little extra for wastage. Confirm the final quantity with your mason or engineer.',
  'calc.brick': 'Brick wall', 'calc.concrete': 'Concrete (RCC)', 'calc.plaster': 'Plaster', 'calc.tiles': 'Floor tiles', 'calc.paint': 'Paint',
  'calc.length': 'Length', 'calc.height': 'Height', 'calc.width': 'Width', 'calc.depth': 'Thickness', 'calc.ft': 'ft', 'calc.in': 'inch',
  'calc.wallThick': 'Wall thickness', 'calc.wall9': '9 inch (full brick)', 'calc.wall4': '4.5 inch (half brick)',
  'calc.brickType': 'Brick', 'calc.red': 'Red clay brick (9 × 4.5 × 3 inch)', 'calc.fly': 'Fly ash brick (230 × 110 × 75 mm)',
  'calc.mortar': 'Mortar mix (cement : sand)', 'calc.openings': 'Doors and windows to leave out (sq ft)',
  'calc.element': 'What are you casting?', 'calc.slab': 'Slab (roof)', 'calc.beam': 'Beam', 'calc.column': 'Column', 'calc.footing': 'Footing',
  'calc.count': 'How many of this size', 'calc.mix': 'Concrete mix',
  'calc.m20': 'M20 (1 : 1.5 : 3) for slab, beam, column', 'calc.m15': 'M15 (1 : 2 : 4) for light work', 'calc.m10': 'M10 (1 : 3 : 6) for PCC base',
  'calc.pThick': 'Plaster thickness', 'calc.p12': '12 mm (inside walls)', 'calc.p15': '15 mm (outside walls)', 'calc.p20': '20 mm (rough surface)',
  'calc.pMix': 'Mix (cement : sand)', 'calc.mix4': '1 : 4 (ceiling, outside)', 'calc.mix5': '1 : 5', 'calc.mix6': '1 : 6 (inside walls)',
  'calc.roomL': 'Room length', 'calc.roomW': 'Room width', 'calc.tileSize': 'Tile size', 'calc.extra': 'Extra for cutting',
  'calc.paintFor': 'Painting', 'calc.inside': 'Inside of a room', 'calc.outside': 'Outside of the house',
  'calc.wallH': 'Wall height', 'calc.ceiling': 'Paint the ceiling too', 'calc.rooms': 'Number of rooms of this size',
  'calc.houseL': 'House length', 'calc.houseW': 'House width',
  'r.need': 'You will need about', 'r.enter': 'Enter the sizes to see the material needed.',
  'r.bricks': 'Bricks', 'r.cement': 'Cement', 'r.sand': 'Sand', 'r.agg': 'Gitti (20 mm)', 'r.steel': 'Sariya (rough guide)',
  'r.tiles': 'Tiles', 'r.adhesive': 'Tile adhesive (20 kg bags)', 'r.paint': 'Paint (2 coats)', 'r.primer': 'Primer (1 coat)', 'r.putty': 'Wall putty (2 coats)',
  'u.bags': 'bags', 'u.pcs': 'pieces', 'u.cft': 'cft', 'u.kg': 'kg', 'u.litre': 'litres', 'u.boxes': 'boxes', 'u.trolley': 'trolley',
  'r.sandSub': '{cft} cft, about {t} tractor trolley', 'r.boxSub': '{n} boxes, {per} tiles a box', 'r.puttySub': '{kg} kg, {b} bags of 40 kg',
  'r.vol': 'Volume {cft} cft ({m3} m³)', 'r.area': 'Area {a} sq ft',
  'r.addList': 'Add to enquiry list', 'r.added': 'Added to your enquiry list', 'r.wa': 'Ask rate on WhatsApp',
  'r.waMsg': 'Namaste {shop}, I need rates for this ({work}):\n{list}', 'r.how': 'How this is worked out',
  'n.brick': 'Bricks are about {n} per m³ of wall including 10 mm mortar joints, plus 5% for breakage. Dry mortar is 1.33 times the wet volume. Cement is 1,440 kg per m³, 50 kg a bag.',
  'n.concrete': 'Dry materials are 1.54 times the concrete volume. Cement is 1,440 kg per m³, 50 kg a bag. Sariya is a thumb rule (slab 1%, beam 2%, column 2.5%, footing 0.8% of the volume); your drawings decide the real quantity.',
  'n.plaster': 'Dry mortar is 1.27 times the wet volume, plus 20% to fill joints and uneven brickwork. One side of the wall only.',
  'n.tiles': 'Tile count includes the extra for cutting and breakage. One 20 kg adhesive bag covers about 45 sq ft of floor.',
  'n.paint': 'Emulsion covers about 55 sq ft per litre inside and 45 outside for two coats; primer about 100 sq ft per litre; putty about 10 sq ft per kg for two coats. Brands differ.',
  'l.brick': 'Red clay brick', 'l.fly': 'Fly ash brick', 'l.cement': 'PPC cement, 50 kg bag', 'l.sand': 'River sand (ret)',
  'l.agg': 'Stone aggregate 20 mm (gitti)', 'l.steel': 'TMT sariya, mixed sizes', 'l.tiles': 'Floor tile {size}', 'l.adhesive': 'Tile adhesive, 20 kg',
  'l.paint': 'Interior emulsion paint', 'l.paintX': 'Exterior emulsion paint', 'l.primer': 'Wall primer', 'l.putty': 'Wall putty, 40 kg',
  't.600': '600 × 600 mm (2 × 2 ft)', 't.800': '800 × 800 mm (2.6 × 2.6 ft)', 't.1200': '600 × 1200 mm (2 × 4 ft)',
  't.300': '300 × 300 mm (1 × 1 ft)', 't.400': '400 × 400 mm (16 × 16 inch)',
  't.x10': '10% (normal room)', 't.x5': '5% (plain square room)', 't.x15': '15% (diagonal laying)'
},

hi: {
  'lang.other': 'English', 'lang.aria': 'View in English',
  'skip': 'सीधे सामग्री पर जाएँ',
  'nav.home': 'होम', 'nav.products': 'सामान', 'nav.calc': 'कैलकुलेटर', 'nav.about': 'हमारे बारे में', 'nav.contact': 'संपर्क',
  'nav.list': 'पूछताछ सूची', 'nav.menu': 'मेनू',
  'f.talk': 'हमसे बात करें', 'f.shop': 'सामान', 'f.whatsapp': 'व्हाट्सऐप',
  'f.note': 'दिखाए गए रेट अनुमानित हैं, ऑर्डर के समय पक्के किए जाते हैं।', 'f.by': 'वेबसाइट:',
  'wa.generic': 'नमस्ते {shop}, मुझे कुछ जानकारी चाहिए।',
  'wa.product': 'नमस्ते {shop}, कृपया आज का रेट और उपलब्धता बताएँ:\n{item}', 'wa.qty': 'मात्रा: {q} {unit}',

  'card.add': 'सूची में जोड़ें', 'card.out': 'स्टॉक में नहीं', 'card.per': 'प्रति {unit}', 'card.ask': 'रेट पूछें',
  'card.waAria': '{name} के बारे में व्हाट्सऐप पर पूछें', 'toast.added': '{name} सूची में जुड़ा', 'toast.view': 'सूची देखें',
  'items.n': '{n} सामान', 'items.1': '1 सामान',

  'title.home': 'शनि ट्रेडर्स | सरायपाली में बिल्डिंग मटेरियल',
  'title.products': 'सामान | शनि ट्रेडर्स, सरायपाली', 'title.enquiry': 'पूछताछ | शनि ट्रेडर्स',
  'title.about': 'हमारे बारे में | शनि ट्रेडर्स', 'title.contact': 'संपर्क | शनि ट्रेडर्स, सरायपाली',
  'title.calc': 'मटेरियल कैलकुलेटर | शनि ट्रेडर्स',

  'h.title': 'नींव से छत तक, मकान का सारा सामान एक ही दुकान पर।',
  'h.alt': 'Everything your building needs, from the foundation up.', 'h.altLang': 'en',
  'h.sub': 'सरायपाली में सीमेंट, सरिया, ईंट, रेत, प्लंबिंग, वायरिंग, टाइल्स और पेंट। अपनी सूची बनाइए, हमें भेजिए, हम सबसे अच्छे रेट और डिलीवरी समय के साथ फ़ोन करेंगे।',
  'h.browse': 'सामान देखें', 'h.wa': 'व्हाट्सऐप पर पूछें', 'h.waMsg': 'नमस्ते {shop}, मुझे बिल्डिंग मटेरियल के आज के रेट चाहिए।',
  'h.rates': 'आज के रेट', 'h.loading': 'रेट लोड हो रहे हैं…', 'h.ratesErr': 'रेट लोड नहीं हो पाए। आज के रेट के लिए कॉल या व्हाट्सऐप करें।',
  'h.rbAsk': 'पूछें', 'h.rbFoot': 'रेट बाज़ार के साथ बदलते हैं। डिलीवरी सहित पक्के रेट के लिए {link}।', 'h.rbLink': 'अपनी सूची भेजें',
  'h.shopBy': 'काम के हिसाब से सामान', 'h.shopBySub': 'अभी जो काम चल रहा है, वो चुनिए। सारा सामान एक ही पूछताछ सूची में जोड़ सकते हैं।',
  'h.askUs': 'हमसे पूछें',
  'h.calcTitle': 'कितना सामान लगेगा, पता नहीं?',
  'h.calcSub': 'दीवार, स्लैब या कमरे का नाप डालिए। कैलकुलेटर बता देगा कितनी ईंट, कितनी बोरी सीमेंट और कितनी ट्रॉली रेत लगेगी।',
  'h.calcBtn': 'कैलकुलेटर खोलें',
  'h.how': 'ऑर्डर कैसे करें',
  'h.s1t': 'अपनी सूची बनाइए', 'h.s1': 'सामान और मात्रा चुनिए, या कैलकुलेटर से निकालिए।',
  'h.s2t': 'हमें भेजिए', 'h.s2': 'सूची व्हाट्सऐप पर या पूछताछ फ़ॉर्म से भेजिए। दोनों सीधे दुकान तक पहुँचते हैं।',
  'h.s3t': 'पक्का रेट पाइए', 'h.s3': 'हम फ़ाइनल रेट, GST बिल और साइट पर डिलीवरी का समय बताने के लिए फ़ोन करते हैं।',
  'h.strip': 'मकान या दुकान बना रहे हैं? पूरी सूची एक बार भेजिए, सारे सामान का एक साथ रेट पाइए।',
  'h.stripBtn': 'पूछताछ शुरू करें',

  'p.title': 'सामान', 'p.sub': 'रेट दिखाई गई इकाई के हिसाब से है। फ़ाइनल रेट मात्रा और डिलीवरी की दूरी पर निर्भर है।',
  'p.searchLbl': 'सामान खोजें', 'p.search': 'सीमेंट, सरिया, ईंट, पाइप खोजें…', 'p.sort': 'क्रम',
  'p.rec': 'सुझाए गए', 'p.low': 'रेट: कम से ज़्यादा', 'p.high': 'रेट: ज़्यादा से कम', 'p.name': 'नाम से',
  'p.all': 'सभी', 'p.cat': 'श्रेणी', 'p.in': '{cat}: {count}',
  'p.none': '“{q}” से कुछ नहीं मिला। हमारे पास और भी सामान है, हमसे पूछिए।', 'p.noneWa': 'नमस्ते {shop}, क्या आपके पास {q} है?',
  'p.err': 'सामान की सूची लोड नहीं हुई। इंटरनेट चेक करके पेज रीफ़्रेश करें, या सीधे हमसे पूछें।',

  'pd.loading': 'लोड हो रहा है…', 'pd.missing': 'यह सामान अभी साइट पर उपलब्ध नहीं है।', 'pd.all': 'सारा सामान देखें',
  'pd.in': 'स्टॉक में है', 'pd.out': 'अभी स्टॉक में नहीं', 'pd.less': 'कम', 'pd.more': 'ज़्यादा', 'pd.qty': 'मात्रा ({unit})',
  'pd.add': 'पूछताछ सूची में जोड़ें', 'pd.wa': 'व्हाट्सऐप पर पूछें', 'pd.waBack': 'कब आएगा, पूछें',
  'pd.brand': 'ब्रांड', 'pd.soldPer': 'बिक्री इकाई', 'pd.cat': 'श्रेणी', 'pd.related': 'इसी श्रेणी का और सामान', 'pd.photo': 'फ़ोटो',

  'e.title': 'आपकी पूछताछ', 'e.sub': 'अपनी सूची भेजिए, हम रेट और डिलीवरी समय बताने के लिए फ़ोन करेंगे। ऑनलाइन कोई भुगतान नहीं लिया जाता।',
  'e.items': 'सामान', 'e.clear': 'सूची खाली करें', 'e.clearQ': 'सूची से सारा सामान हटाएँ?',
  'e.empty': 'आपकी सूची खाली है। सामान जोड़िए, कैलकुलेटर इस्तेमाल कीजिए, या नीचे संदेश में लिख दीजिए।',
  'e.remove': 'हटाएँ', 'e.sendWa': 'यह सूची व्हाट्सऐप पर भेजें', 'e.waMsg': 'नमस्ते {shop}, कृपया इनका रेट बताएँ:\n{list}',
  'e.browse': 'सामान देखें', 'e.details': 'आपकी जानकारी', 'e.name': 'नाम', 'e.phone': 'मोबाइल नंबर', 'e.phonePh': '10 अंकों का नंबर',
  'e.place': 'गाँव या शहर', 'e.delivery': 'डिलीवरी', 'e.d1': 'मेरी साइट पर पहुँचाएँ', 'e.d2': 'दुकान से ले जाऊँगा', 'e.d3': 'अभी तय नहीं',
  'e.email': 'ईमेल', 'e.optional': '(ज़रूरी नहीं)', 'e.emailHint': 'आपकी पूछताछ की कॉपी यहाँ भेजेंगे।',
  'e.msg': 'और कुछ?', 'e.msgPh': 'जो सामान साइट पर नहीं है, मकान का साइज़, सामान कब चाहिए…',
  'e.send': 'पूछताछ भेजें', 'e.sending': 'भेज रहे हैं…',
  'e.errName': 'अपना नाम लिखें।', 'e.errPhone': '10 अंकों का मोबाइल नंबर लिखें।', 'e.errEmpty': 'सूची में सामान जोड़ें या संदेश में लिखें कि क्या चाहिए।',
  'e.done': 'पूछताछ भेज दी गई', 'e.doneMsg': 'आपका रेफ़रेंस नंबर {id} है। हम जल्द ही {phone} पर फ़ोन करेंगे।', 'e.doneMail': ' कॉपी आपके ईमेल पर भेजी जा रही है।',
  'e.back': 'सामान पर वापस', 'e.errAlt': 'आप इसे {link} भी सकते हैं।', 'e.errLink': 'व्हाट्सऐप पर भेज',
  'e.waForm': 'नमस्ते {shop}, नई पूछताछ\nनाम: {name}\nमोबाइल: {phone}\nजगह: {place}\nडिलीवरी: {delivery}\n\n{list}\n\n{msg}',

  'a.title': 'शनि ट्रेडर्स के बारे में',
  'a.lead': 'शनि ट्रेडर्स सरायपाली और आसपास के परिवारों, दुकानदारों और ठेकेदारों को बिल्डिंग मटेरियल देता है, सीमेंट की पहली बोरी से पेंट के आख़िरी कोट तक।',
  'a.p': 'हमारी दुकान मेन रोड, पटसेंद्री पर है। मकान के हर चरण का सामान हमारे पास है, ताकि आप पाँच दुकानों के बजाय एक ही जगह से ख़रीदें, एक बिल और एक डिलीवरी शेड्यूल के साथ।',
  'a.f1t': 'भरोसेमंद ब्रांड', 'a.f1': 'सीमेंट, सरिया, पाइप, वायर और पेंट उन ब्रांड्स के, जिन पर मिस्त्री और इंजीनियर भरोसा करते हैं।',
  'a.f2t': 'हर ऑर्डर पर GST बिल', 'a.f2': 'हर ख़रीद पर पक्का टैक्स इनवॉइस, होम लोन और बिज़नेस के हिसाब के लिए काम का।',
  'a.f3t': 'साइट पर डिलीवरी', 'a.f3': 'रेत, गिट्टी, ईंट और भारी सामान ट्रैक्टर और पिकअप से आपकी साइट तक।',
  'a.f4t': 'सही रोज़ाना रेट', 'a.f4': 'रेट बाज़ार के हिसाब से। ख़रीदने से पहले पूछिए, हम आपकी मात्रा का रेट बताएँगे।',
  'a.btn': 'सामान देखें',

  'c.title': 'संपर्क', 'c.sub': 'कॉल कीजिए, व्हाट्सऐप कीजिए या दुकान पर आइए।', 'c.address': 'पता', 'c.phone': 'फ़ोन', 'c.email': 'ईमेल',
  'c.hours': 'दुकान का समय', 'c.gstin': 'GSTIN', 'c.call': 'दुकान पर कॉल करें', 'c.form': 'पूछताछ फ़ॉर्म', 'c.map': 'नक्शे पर दुकान',

  'calc.title': 'मटेरियल कैलकुलेटर',
  'calc.sub': 'नाप फ़ुट में डालिए। नतीजों में वेस्टेज के लिए थोड़ा अतिरिक्त जोड़ा गया है। फ़ाइनल मात्रा अपने मिस्त्री या इंजीनियर से पक्की करें।',
  'calc.brick': 'ईंट की दीवार', 'calc.concrete': 'ढलाई (RCC)', 'calc.plaster': 'प्लास्टर', 'calc.tiles': 'फ़र्श टाइल्स', 'calc.paint': 'पेंट',
  'calc.length': 'लंबाई', 'calc.height': 'ऊँचाई', 'calc.width': 'चौड़ाई', 'calc.depth': 'मोटाई', 'calc.ft': 'फ़ुट', 'calc.in': 'इंच',
  'calc.wallThick': 'दीवार की मोटाई', 'calc.wall9': '9 इंच (पूरी ईंट)', 'calc.wall4': '4.5 इंच (आधी ईंट)',
  'calc.brickType': 'ईंट', 'calc.red': 'लाल ईंट (9 × 4.5 × 3 इंच)', 'calc.fly': 'फ्लाई ऐश ईंट (230 × 110 × 75 मिमी)',
  'calc.mortar': 'मसाला (सीमेंट : रेत)', 'calc.openings': 'दरवाज़े-खिड़की, जो घटाने हैं (वर्ग फ़ुट)',
  'calc.element': 'क्या ढालना है?', 'calc.slab': 'स्लैब (छत)', 'calc.beam': 'बीम', 'calc.column': 'कॉलम', 'calc.footing': 'फ़ुटिंग (नींव)',
  'calc.count': 'इस नाप के कितने', 'calc.mix': 'मिक्स',
  'calc.m20': 'M20 (1 : 1.5 : 3) स्लैब, बीम, कॉलम के लिए', 'calc.m15': 'M15 (1 : 2 : 4) हल्के काम के लिए', 'calc.m10': 'M10 (1 : 3 : 6) PCC बेस के लिए',
  'calc.pThick': 'प्लास्टर की मोटाई', 'calc.p12': '12 मिमी (अंदर की दीवार)', 'calc.p15': '15 मिमी (बाहर की दीवार)', 'calc.p20': '20 मिमी (खुरदरी सतह)',
  'calc.pMix': 'मसाला (सीमेंट : रेत)', 'calc.mix4': '1 : 4 (छत के नीचे, बाहर)', 'calc.mix5': '1 : 5', 'calc.mix6': '1 : 6 (अंदर की दीवार)',
  'calc.roomL': 'कमरे की लंबाई', 'calc.roomW': 'कमरे की चौड़ाई', 'calc.tileSize': 'टाइल का साइज़', 'calc.extra': 'कटिंग के लिए अतिरिक्त',
  'calc.paintFor': 'कहाँ पेंट करना है', 'calc.inside': 'कमरे के अंदर', 'calc.outside': 'मकान के बाहर',
  'calc.wallH': 'दीवार की ऊँचाई', 'calc.ceiling': 'छत (सीलिंग) भी पेंट करनी है', 'calc.rooms': 'इस नाप के कितने कमरे',
  'calc.houseL': 'मकान की लंबाई', 'calc.houseW': 'मकान की चौड़ाई',
  'r.need': 'लगभग इतना लगेगा', 'r.enter': 'ज़रूरी सामान देखने के लिए नाप डालिए।',
  'r.bricks': 'ईंट', 'r.cement': 'सीमेंट', 'r.sand': 'रेत', 'r.agg': 'गिट्टी (20 मिमी)', 'r.steel': 'सरिया (मोटा अनुमान)',
  'r.tiles': 'टाइल्स', 'r.adhesive': 'टाइल एडहेसिव (20 किलो बोरी)', 'r.paint': 'पेंट (2 कोट)', 'r.primer': 'प्राइमर (1 कोट)', 'r.putty': 'वॉल पुट्टी (2 कोट)',
  'u.bags': 'बोरी', 'u.pcs': 'नग', 'u.cft': 'घन फ़ुट', 'u.kg': 'किलो', 'u.litre': 'लीटर', 'u.boxes': 'डिब्बे', 'u.trolley': 'ट्रॉली',
  'r.sandSub': '{cft} घन फ़ुट, लगभग {t} ट्रैक्टर ट्रॉली', 'r.boxSub': '{n} डिब्बे, एक डिब्बे में {per} टाइल', 'r.puttySub': '{kg} किलो, 40 किलो की {b} बोरी',
  'r.vol': 'आयतन {cft} घन फ़ुट ({m3} घन मीटर)', 'r.area': 'क्षेत्रफल {a} वर्ग फ़ुट',
  'r.addList': 'पूछताछ सूची में जोड़ें', 'r.added': 'पूछताछ सूची में जोड़ दिया', 'r.wa': 'व्हाट्सऐप पर रेट पूछें',
  'r.waMsg': 'नमस्ते {shop}, इसके लिए रेट चाहिए ({work}):\n{list}', 'r.how': 'कैसे निकाला गया',
  'n.brick': '10 मिमी जोड़ के साथ 1 घन मीटर दीवार में लगभग {n} ईंट, 5% टूट-फूट अतिरिक्त। सूखा मसाला गीले मसाले का 1.33 गुना। सीमेंट 1,440 किलो प्रति घन मीटर, 50 किलो की बोरी।',
  'n.concrete': 'सूखा सामान ढलाई के आयतन का 1.54 गुना। सीमेंट 1,440 किलो प्रति घन मीटर, 50 किलो की बोरी। सरिया सिर्फ़ अंदाज़ा है (स्लैब 1%, बीम 2%, कॉलम 2.5%, फ़ुटिंग 0.8%); असली मात्रा नक्शे से तय होती है।',
  'n.plaster': 'सूखा मसाला गीले का 1.27 गुना, और जोड़ व ऊबड़-खाबड़ सतह भरने के लिए 20% अतिरिक्त। दीवार की सिर्फ़ एक तरफ़।',
  'n.tiles': 'टाइल्स में कटिंग और टूट-फूट का अतिरिक्त जुड़ा है। 20 किलो एडहेसिव लगभग 45 वर्ग फ़ुट फ़र्श के लिए।',
  'n.paint': 'इमल्शन 2 कोट में अंदर लगभग 55 और बाहर 45 वर्ग फ़ुट प्रति लीटर; प्राइमर लगभग 100 वर्ग फ़ुट प्रति लीटर; पुट्टी 2 कोट में लगभग 10 वर्ग फ़ुट प्रति किलो। ब्रांड के हिसाब से बदलता है।',
  'l.brick': 'लाल ईंट', 'l.fly': 'फ्लाई ऐश ईंट', 'l.cement': 'PPC सीमेंट, 50 किलो बोरी', 'l.sand': 'नदी की रेत',
  'l.agg': 'गिट्टी 20 मिमी', 'l.steel': 'TMT सरिया, अलग-अलग साइज़', 'l.tiles': 'फ़र्श टाइल {size}', 'l.adhesive': 'टाइल एडहेसिव, 20 किलो',
  'l.paint': 'अंदर का इमल्शन पेंट', 'l.paintX': 'बाहर का इमल्शन पेंट', 'l.primer': 'वॉल प्राइमर', 'l.putty': 'वॉल पुट्टी, 40 किलो',
  't.600': '600 × 600 मिमी (2 × 2 फ़ुट)', 't.800': '800 × 800 मिमी (2.6 × 2.6 फ़ुट)', 't.1200': '600 × 1200 मिमी (2 × 4 फ़ुट)',
  't.300': '300 × 300 मिमी (1 × 1 फ़ुट)', 't.400': '400 × 400 मिमी (16 × 16 इंच)',
  't.x10': '10% (सामान्य कमरा)', 't.x5': '5% (सीधा चौकोर कमरा)', 't.x15': '15% (तिरछी बिछाई)'
}
};

/* Units as written in the "Sold per" column, shown in Hindi */
window.UNITS_HI = {
  bag: 'बोरी', kg: 'किलो', piece: 'नग', trolley: 'ट्रॉली', tonne: 'टन', cft: 'घन फ़ुट', 'sq ft': 'वर्ग फ़ुट',
  box: 'डिब्बा', coil: 'बंडल', length: 'लंबाई', litre: 'लीटर', bucket: 'बाल्टी', bottle: 'बोतल', unit: 'इकाई'
};
